import { DropOffLocation, Challenge, Badge, UserProfile, UserActionLog, ScanResult } from '../src/types';

export const INITIAL_USER: UserProfile = {
  id: 'usr_default',
  name: 'Alex Rivera',
  email: 'alex.rivera@ecoverse.org',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
  organization: 'Tech For Green Campus',
  orgType: 'campus',
  ecoPoints: 460,
  ecoLevel: 'Eco Hero',
  nextLevelPoints: 700,
  itemsRecycled: 18,
  itemsReused: 7,
  itemsDonated: 5,
  itemsSafelyDisposed: 4,
  totalWasteDivertedKg: 28.4,
  totalCo2AvoidedKg: 64.2,
  streakDays: 6,
  createdAt: '2026-08-15T10:00:00Z',
  badges: [
    {
      id: 'badge_first_scan',
      title: 'First Step',
      description: 'Completed your first AI waste scan',
      icon: 'Camera',
      unlockedAt: '2026-08-15T11:20:00Z',
      category: 'milestone',
      requirement: '1 item scanned',
    },
    {
      id: 'badge_ewaste_guardian',
      title: 'E-Waste Guardian',
      description: 'Safely recycled or disposed of 3 electronic devices or batteries',
      icon: 'Cpu',
      unlockedAt: '2026-09-02T14:10:00Z',
      category: 'category',
      requirement: '3 e-waste items processed',
    },
    {
      id: 'badge_zero_landfill',
      title: 'Zero-Landfill Hero',
      description: 'Diverted over 20kg of materials away from incinerators and landfills',
      icon: 'ShieldCheck',
      unlockedAt: '2026-09-28T09:45:00Z',
      category: 'milestone',
      requirement: '20kg waste diverted',
    },
    {
      id: 'badge_upcycle_creator',
      title: 'Upcycle Alchemist',
      description: 'Gave a creative second life to discarded goods',
      icon: 'Sparkles',
      unlockedAt: '2026-10-01T16:30:00Z',
      category: 'milestone',
      requirement: 'Log 2 upcycle projects',
    },
  ],
};

export const INITIAL_LOCATIONS: DropOffLocation[] = [
  {
    id: 'loc_1',
    name: 'GreenTech Metro E-Waste Depository',
    type: 'E-Waste Hub',
    categoryKey: 'e_waste',
    address: '450 Innovation Parkway, Suite 12B',
    distanceKm: 1.4,
    lat: 37.7749,
    lng: -122.4194,
    supportedCategories: ['electronics', 'batteries'],
    isOpen: true,
    hours: 'Mon-Sat 8:00 AM – 6:00 PM',
    phone: '(555) 234-8901',
    rating: 4.9,
    acceptsPublic: true,
  },
  {
    id: 'loc_2',
    name: 'Central Municipal Circular Resource Center',
    type: 'Recycling Center',
    categoryKey: 'recycling',
    address: '890 Riverside Avenue, Dock 4',
    distanceKm: 2.1,
    lat: 37.7812,
    lng: -122.4088,
    supportedCategories: ['plastic', 'glass', 'metal', 'paper', 'food_containers'],
    isOpen: true,
    hours: 'Open Daily 7:00 AM – 7:00 PM',
    phone: '(555) 345-6789',
    rating: 4.7,
    acceptsPublic: true,
  },
  {
    id: 'loc_3',
    name: 'Second Chance Goodwill Community Hub',
    type: 'Donation Center',
    categoryKey: 'donation',
    address: '120 Market Street, Center Plaza',
    distanceKm: 0.8,
    lat: 37.7690,
    lng: -122.4280,
    supportedCategories: ['textiles', 'electronics'],
    isOpen: true,
    hours: 'Mon-Sun 9:00 AM – 5:30 PM',
    phone: '(555) 987-6543',
    rating: 4.8,
    acceptsPublic: true,
  },
  {
    id: 'loc_4',
    name: 'VoltSafe Battery & Chemical Drop-off',
    type: 'Battery Drop-Off',
    categoryKey: 'batteries',
    address: '315 Industrial Way, Gate 3',
    distanceKm: 3.2,
    lat: 37.7610,
    lng: -122.4010,
    supportedCategories: ['batteries', 'medicines'],
    isOpen: true,
    hours: 'Tue-Sat 9:00 AM – 4:00 PM',
    phone: '(555) 876-5432',
    rating: 4.6,
    acceptsPublic: true,
  },
  {
    id: 'loc_5',
    name: 'ThreadLoop Circular Fashion & Textile Vault',
    type: 'Textile Collection',
    categoryKey: 'textiles',
    address: '622 Fashion Blvd, District 7',
    distanceKm: 1.9,
    lat: 37.7880,
    lng: -122.4230,
    supportedCategories: ['textiles'],
    isOpen: true,
    hours: 'Daily 10:00 AM – 8:00 PM',
    phone: '(555) 432-1098',
    rating: 4.9,
    acceptsPublic: true,
  },
  {
    id: 'loc_6',
    name: 'County Hazardous & Pharmaceutical Safe Depot',
    type: 'Hazardous Disposal',
    categoryKey: 'safe_disposal',
    address: '1040 Perimeter Road, Facility B',
    distanceKm: 4.5,
    lat: 37.7550,
    lng: -122.3920,
    supportedCategories: ['medicines', 'batteries', 'electronics'],
    isOpen: false,
    hours: 'Mon-Fri 8:30 AM – 4:30 PM (Closed Weekends)',
    phone: '(555) 765-4321',
    rating: 4.5,
    acceptsPublic: true,
  },
];

export const INITIAL_CHALLENGES: Challenge[] = [
  {
    id: 'chal_1',
    title: 'Autumn E-Waste Zero Cleanout',
    description: 'Safely recycle or donate 5 unused electronics, cords, or old gadgets.',
    targetCount: 5,
    targetCategory: 'electronics',
    targetAction: 'all',
    pointsReward: 120,
    badgeReward: 'Tech Recycler Star',
    currentProgress: 3,
    joined: true,
    completed: false,
    participantsCount: 418,
    daysRemaining: 8,
    categoryBadge: 'E-Waste',
  },
  {
    id: 'chal_2',
    title: 'Plastic Bottle Circular Sprint',
    description: 'Keep 10 plastic beverage or detergent bottles out of waterways.',
    targetCount: 10,
    targetCategory: 'plastic',
    targetAction: 'recycle',
    pointsReward: 100,
    badgeReward: 'Ocean Defender',
    currentProgress: 7,
    joined: true,
    completed: false,
    participantsCount: 892,
    daysRemaining: 14,
    categoryBadge: 'Plastic',
  },
  {
    id: 'chal_3',
    title: 'Textile Upcycle Challenge',
    description: 'Convert or donate 3 garments instead of throwing them away.',
    targetCount: 3,
    targetCategory: 'textiles',
    targetAction: 'all',
    pointsReward: 90,
    badgeReward: 'Fashion Forward',
    currentProgress: 1,
    joined: false,
    completed: false,
    participantsCount: 265,
    daysRemaining: 19,
    categoryBadge: 'Textiles',
  },
  {
    id: 'chal_4',
    title: 'Battery Safe Quarantine',
    description: 'Bring 4 lithium or alkaline cells to a certified hazardous drop-off point.',
    targetCount: 4,
    targetCategory: 'batteries',
    targetAction: 'safe_disposal',
    pointsReward: 150,
    badgeReward: 'Volt Protector',
    currentProgress: 2,
    joined: true,
    completed: false,
    participantsCount: 531,
    daysRemaining: 11,
    categoryBadge: 'Hazardous',
  },
];

export const INITIAL_LOGS: UserActionLog[] = [
  {
    id: 'act_101',
    userId: 'usr_default',
    scanId: 'scn_1',
    itemName: 'Lithium-Ion Laptop Battery Pack',
    category: 'batteries',
    chosenAction: 'safe_disposal',
    actionTitle: 'Terminals taped and brought to VoltSafe Depot',
    pointsEarned: 35,
    co2SavedKg: 3.8,
    wasteDivertedKg: 0.65,
    confirmedAt: '2026-10-04T14:30:00Z',
  },
  {
    id: 'act_102',
    userId: 'usr_default',
    scanId: 'scn_2',
    itemName: 'Frayed USB-C Power Adapter',
    category: 'electronics',
    chosenAction: 'recycle',
    actionTitle: 'Deposited into GreenTech E-Waste bin',
    pointsEarned: 25,
    co2SavedKg: 2.1,
    wasteDivertedKg: 0.22,
    confirmedAt: '2026-10-03T11:15:00Z',
  },
  {
    id: 'act_103',
    userId: 'usr_default',
    scanId: 'scn_3',
    itemName: 'Clear PET Water Bottle (1.5L)',
    category: 'plastic',
    chosenAction: 'recycle',
    actionTitle: 'Rinsed, cap removed, placed in blue recycling stream',
    pointsEarned: 15,
    co2SavedKg: 0.45,
    wasteDivertedKg: 0.08,
    confirmedAt: '2026-10-02T09:40:00Z',
  },
  {
    id: 'act_104',
    userId: 'usr_default',
    scanId: 'scn_4',
    itemName: 'Old Cotton Denim Jacket',
    category: 'textiles',
    chosenAction: 'donate',
    actionTitle: 'Delivered to Second Chance Community Hub',
    pointsEarned: 30,
    co2SavedKg: 8.5,
    wasteDivertedKg: 1.1,
    confirmedAt: '2026-09-30T16:20:00Z',
  },
  {
    id: 'act_105',
    userId: 'usr_default',
    scanId: 'scn_5',
    itemName: 'Glass Olive Oil Bottle',
    category: 'glass',
    chosenAction: 'upcycle',
    actionTitle: 'Cleaned and transformed into botanical plant propagator',
    pointsEarned: 25,
    co2SavedKg: 1.2,
    wasteDivertedKg: 0.45,
    confirmedAt: '2026-09-28T13:00:00Z',
  },
];
